
```{r}
fuel_test <- data.frame(
  time = c("2019", "2019", "2019", "2019", "2020", "2020", "2020", "2020"),
  site = c("SEKI", "SEKI", "SEKI","SEKI", "SEKI", "SEKI", "SEKI", "SEKI"),
  plot = c("1", "1", "2", "2", "1", "1", "2", "2"),
  transect = c("90", "120", "90", "120", "90", "120", "20", "120"),
  count_1h = c(12, 30, 10, 2, 5, 14, 9, 6),
  count_10h = c(4,8,3,2,9,4,3,3),
  count_100h = c(5,7,10,11,6,3,13,9),
  length_1h = c(2,2,2,2,2,2,2,2),
  length_10h = c(4,4,4,4,4,4,4,4),
  length_100h = c(15,15,15,15,15,15,15,15),
  slope = c(10,20,15,5,10,20,15,5)
)

duff_test <- data.frame(
  time = c("2019", "2019", "2019", "2019", "2020", "2020", "2020", "2020"),
  site = c("SEKI", "SEKI", "SEKI","SEKI", "SEKI", "SEKI", "SEKI", "SEKI"),
  plot = c("1", "1", "2", "2", "1", "1", "2", "2"),
  transect = c("90", "120", "90", "120", "90", "120", "90", "120"),
  litter_depth = c(2,3,6,7,5,5,3,6),
  duff_depth = c(5,1,3,2,4,4,2,1),
  lit_duff_depth = c(7,4,9,9,9,9,5,7)
)

duff_test2 <- data.frame(
  time = c("2019", "2019", "2019", "2019", "2020", "2020", "2020", "2020"),
  site = c("SEKI", "SEKI", "SEKI","SEKI", "SEKI", "SEKI", "SEKI", "SEKI"),
  plot = c("1", "1", "2", "2", "1", "1", "2", "2"),
  transect = c("90", "90", "90", "90", "90", "90", "90", "120"),
  litter_depth = c(2,3,6,7,5,5,3,6),
  duff_depth = c(5,1,3,2,4,4,2,1),
  lit_duff_depth = c(7,4,9,9,9,9,5,7)
)

tree_test <- data.frame(
  time = c("2019", "2019", "2019", "2019", "2019", "2019", "2019", "2020", "2020", "2020", "2020", "2020", "2020", "2020"),
  site = c("SEKI", "SEKI", "SEKI","SEKI", "SEKI", "SEKI", "SEKI", "SEKI", "SEKI","SEKI", "SEKI", "SEKI", "SEKI", "SEKI"),
  plot = as.character(c(1,1,1,2,2,2,2,1,1,1,2,2,2,2)),
  exp_factor = c(50,50,50,50,50,50,50,50,50,50,50,50,50,50),
  species = c("UNTR", "ABCO", "ABCO", "PSME", "CADE", "CADE", "CADE", "PSME", "ABCO", "ABCO", "PSME", "CADE", "CADE", "CADE"),
  dbh = c(13.5, 10.3, 19.1, 32.8, 13.8, 20.2, 31.7, 10.3, 44.7, 19.1, 32.8, 13.8, 20.2, 31.7)
)
```


```{r}
ValidateGround(fuel_data_val = duff_test2,
            units_val = "metric",
            meas_val = "separate")
```


```{r}
cwd_test <- data.frame(
  time = c("2019", "2019", "2019", "2020", "2020", "2020", "2020"),
  site = c("SEKI", "SEKI","SEKI", "SEKI", "SEKI", "SEKI", "SEKI"),
  plot = c("1", "2", "2", "1", "1", "2", "2"),
  transect = c("90", "90", "90", "90", "90", "90", "90"),
  diameter = c(0,15,9,10,20,31,16),
  status = c("R","S","R","R","S","S","S"),
  length_1000h = c(2,3,3,2,2,5,5),
  slope = c(0,2,2,0,0,0,0)
)

cwd_test
```

```{r}
ValidateCWD(cwd_test, "metric", "no")
```



